### ISSUE TITLE
Issues with going live

### ISSUE THREAD

**Issue by samuraiKen** [okezieokpara/FlutterWave.RavePay.Net#21]
Awesome .Net library for rave API. However, during integration and testing, I discovered I was unable to go live because of a persistent INVALID PUBLIC KEY ERROR the library returned.

Below is the raw code without refactoring:

===================================================================

public async void chargecard()
{
var raveConfig = new RavePayConfig("FLWPUBK-69dd4afe3cf6de390bf3c8f755244e24-X",
"FLWSECK-d18452a2f01ad26305f7a2a5ffe24305-X", true);
// The second(boolean) paramater toggles between live and test mode. The default value is false

var cardCharge = new RaveCardCharge(raveConfig);

//Creating Instance of Card Class
var debitCard = new Card("5399831125815419", "04", "19", "892");

var cardParams = new CardChargeParams("FLWPUBK-69dd4afe3cf6de390bf3c8f755244e24-X", "Nkenchor", "Osemeke", "nkenchorr@gmail.com",
4556, debitCard)
{
TxRef = Guid.NewGuid().ToString()
};

// make a charge request.
var chargeResponse = await cardCharge.Charge(cardParams);

// Then you can query the charge response. Especially to find the 'Suggested Auth' Property:
//if (chargeResponse.Message == "AUTH_SUGGESTION" && chargeResponse.Data.SuggestedAuth == "PIN")
//{
// cardParams.Pin = "3310";
// cardParams.Otp = "12345";
// cardParams.SuggestedAuth = "PIN";

// // Since the suggested auth was 'pin' we make a second request. Sending the pin and otp.
// chargeResponse = cardCharge.Charge(cardParams).Result;
//}

}

=========================================================================

I investigated the result from the charge task executed by the library and I got INVALID PUBLIC KEY ERROR

==========================================================================

public override async Task<RaveApiResponse<CardResponseData>> Charge(IChargeParams chargeParams, bool isRecurring = false)
{
var encryptedKey = PaymentDataEncryption.GetEncryptionKey(Config.SecretKey);
var encryptedData = PaymentDataEncryption.EncryptData(encryptedKey, JsonConvert.SerializeObject(chargeParams));

var content = new StringContent(JsonConvert.SerializeObject(new { PBFPubKey = chargeParams.PbfPubKey, client = encryptedData, alg = "3DES-24" }), Encoding.UTF8, "application/json");

var requestMessage = new HttpRequestMessage(HttpMethod.Post, Enpoints.CardCharge) { Content = content };
var result = await ApiRequest.Request(requestMessage); // Todo: Check endpoints

// try to get the auth mode used. expected values are: "PIN","VBVSECURECODE", "AVS_VBVSECURECODE"
return result;
}

===================================================================
With little more tests, I discovered that the variable "isLive" was initialized each time there was an instance of the RavePayConfig Class so I made the following adjustments:
N.B. Do not forget to add the appropriate packages via PM to make this work as identified by the authors of this library. 

/// Modified by SamuraiKen on Friday 16.03.2018 @ 2pm 
/// Made isLive, PbfPubKey and SecretKey public static properties to enable live transactions 
/// Handled the persistent test bool variable 
/// This modification was to fix the go live error I faced during integration while differentiating between test and live transactions
/// Took care of references made by RaveCard Charge, RavePayApiRequestBase, RavePreAuthCard, RaveCurrencyService */
/// Modified by SamuraiKen on Friday 16.03.2018 @ 2pm 

namespace Flutterwave.Ravepay.Net
{
    public class RavePayConfig
    {
        public RavePayConfig(bool isLive)
        {
            IsLive = IsLive ? IsLive : isLive;
        }

        /// <summary>
        /// Instansiate a new config object
        /// </summary>
        /// <param name="publicKey">PBFPubKey</param>
        /// <param name="secretKey">This is a unique key generated for each button created on Rave’s dashboard. It starts with a prefix FLWSECK and ends with suffix X</param>
        /// <param name="isLive">Toogle Test and live. Default is false</param>
        public RavePayConfig(string publicKey, string secretKey, bool isLive)
        {
            IsLive = isLive;
            PbfPubKey = publicKey;
            SecretKey = secretKey;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="publicKey">PBFPubKey</param>
        /// <param name="isLive">Toogle Test and live. Default is false</param>
        public RavePayConfig(string publicKey, bool isLive)
        {
            IsLive = isLive;
            PbfPubKey = publicKey;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="publicKey">PBFPubKey</param>
        /// <param name="secretKey">This is a unique key generated for each button created on Rave’s dashboard. It starts with a prefix FLWSECK and ends with suffix X</param>
        public RavePayConfig(string publicKey, string secretKey)
        {
            IsLive = false;
            PbfPubKey = publicKey;
            SecretKey = secretKey;
        }
        public static bool IsLive { get; set; }
        public static string PbfPubKey { get; set; }
        public static string SecretKey { get; set; }
    }
}
/* Modified by SamuraiKen on Friday 16.03.2018 @ 2pm */
/* Made isLive, PbfPubKey and SecretKey public static properties to enable live transactions */
/* Handled the persistent test bool variable */
/* This modification was to fix the go live error I faced during integration while differentiating between test and live transactions*/
/* Took care of references made by RaveCardCharge, RavePayApiRequestBase, RavePreAuthCard, RaveCurrencyService */
/* Modified by SamuraiKen on Friday 16.03.2018 @ 2pm */

=======================================================

Do not forget to add the appropriate packages to make this work as identified by the authors of this library.

**Comment by okezieokpara** [comment]
Thanks @samuraiKen, this will be shortly looked into

**Comment by okezieokpara** [comment]
If you are using the latest version. Then this shouldn't be a problem

**Comment by samuraiKen** [comment]
Okay. It was the latest version I used as at the time of the test.

**Comment by okezieokpara** [comment]
Hello, I have solved this issue, you will need to update to the latest version
The issue is with this class: `RavePayApiRequest<T1, T2>` the constructors weren't calling the appropriate base constructors.

**Comment by samuraiKen** [comment]
Okay thanks. I'll check it out.
